name: Test, Build and Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
#      - run: flutter build apk --debug --split-per-abi
      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        # ref: https://levelup.gitconnected.com/ci-cd-for-flutter-apps-3a56e3fc6d8e
        with:
#          artifacts: "build/app/outputs/apk/debug/*.apk,build/ios/iphoneos/*.app"
          artifacts: "build/ios/iphoneos/*.app"
          token: ${{ secrets.TOKEN }}
          tag: v0.0.2
      # build Flutter web version
      - run: flutter build web
      - name: Push web to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/web